# general settings
name: train_SwinIR_SRx4_scratch_rain_d4PDF_woaugmentation
model_type: SwinIRModel
scale: 4
num_gpu: auto
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: Rain-Train
    type: PairedRainDataset
    dataroot_gt: ../../Data/HR/d4PDF/train #高解像度データのパス
    dataroot_lq: ../../Data/LR/d4PDF/train #低解像度データのパス
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 64 #高解像度画像のサイズ
    use_hflip: false #augmentationの設定
    use_rot: false #augmentationの設定

    # data loader
    num_worker_per_gpu: 6
    batch_size_per_gpu: 32
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

    normalize: #正規化の設定．白石さんが上限を20mmに設定していたので合わせる
      upper_bound: 20

  val:
    name: Rain-Val
    type: PairedRainDataset
    dataroot_gt: ../../Data/HR/d4PDF/val
    dataroot_lq: ../../Data/LR/d4PDF/val
    io_backend:
      type: disk
    
    normalize:
      upper_bound: 20
  


# network structures
# 超解像モデルのパラメータ設定
network_g:
  type: SwinIR
  upscale: 4
  in_chans: 1
  img_size: 16 #元は48
  window_size: 8
  img_range: 1.
  depths: [6, 6, 6, 6, 6, 6]
  embed_dim: 180
  num_heads: [6, 6, 6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [2500, 5000, 7500, 10000, 12500]
    gamma: 0.5

  total_iter: 15000
  warmup_iter: -1  # no warm up

  # losses
  # 白石さんが損失関数にMSEを使っていたので合わせた
  pixel_opt:
    type: MSELoss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e2
  save_img: False

  # metrics:
  #   psnr: # metric name, can be arbitrary
  #     type: calculate_psnr
  #     crop_border: 4
  #     test_y_channel: false
    # ssim: # metric name, can be arbitrary
    #   type: calculate_ssim
    #   crop_border: 4
    #   test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e2
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
